        pipeline  {
                agent { label 'slave-1' }

                parameters {
                    string(name: 'NAME', default: '', description: 'Please enter ypur name')
                    booleanParam(name: '', default: '', description: '')
                    choice(name: 'BRANCH', choices: ['main','master','three','four'], description: '')
                }
                stages {
                    stage('stage 1') {
                        steps {
                            sh 'sleep 5'
                            echo "this is stage 1"
                        }
                    }
                    stage('stage 2') {
                        steps {
                            sh '''
                                #!/bin/bash
                                pwd
                                ls -lrt
                                sleep 5
                            '''
                        }
                    }
                }

        }