        pipeline  {
                agent { label 'slave-1' }

                parameters {
                    string(name: 'NAME', defaultValue: '', description: 'Please enter ypur name')
                    booleanParam(name: 'SKIP_TEST', defaultValue: '', description: 'to skip test ennv and deploy directly ')
                    choice(name: 'BRANCH', choices: ['main','master','prod','four'], description: '')
                }
                stages {
                    stage('stage 1') {
                        steps {
                         echo "STRING NAME: ${params.NAME}"
                         echo "BOOLEAN PARAMETER ${params.SKIP_TEST}"
                         echo "BRANCH CHOOSEN : ${params.BRANCH}"
                         

                        }
                    }
                    
                }

        }